# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    task.query:
        class: Application\Task\Query
        autowire: true

    repository.task_repository:
        class: Infrastructure\Persistence\DoctrineORM\Repository\TaskRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['Domain\Task']

    command.task:
        class: Cli\CliBundle\Command\TaskListCommand
        autowire: true
        tags:
            - { name: console.command }