# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    task.query:
        class: Todo\Application\Task\Query
        autowire: true

    task.command:
        class: Todo\Application\Task\Command
        autowire: true

    repository.task_repository:
        class: Todo\Infrastructure\Persistence\DoctrineORM\Repository\TaskRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['Todo\Domain\Task']

    command.task.list:
        class: Todo\Cli\CliBundle\Command\TaskListCommand
        autowire: true
        tags:
            - { name: console.command }

    command.task.create:
        class: Todo\Cli\CliBundle\Command\TaskCreateCommand
        autowire: true
        tags:
            - { name: console.command }

    command.task.complete:
        class: Todo\Cli\CliBundle\Command\TaskCompleteCommand
        autowire: true
        tags:
            - { name: console.command }


    command.task.redo:
        class: Todo\Cli\CliBundle\Command\TaskRedoCommand
        autowire: true
        tags:
            - { name: console.command }


    command.task.update:
        class: Todo\Cli\CliBundle\Command\TaskUpdateCommand
        autowire: true
        tags:
            - { name: console.command }


    command.task.clean:
        class: Todo\Cli\CliBundle\Command\TaskCleanCommand
        autowire: true
        tags:
            - { name: console.command }
